### ISSUE TITLE
where* evaluates predicate expression every time

### ISSUE THREAD

**Issue by aphyr** [aphyr/riemann#381]
We should bind where*'s predicate expression using let, then call that bound value as a function with each event.

**Comment by AeroNotix** [comment]
This seems like it has been done?

**Comment by aphyr** [comment]
Naw, not yet.

**Comment by AeroNotix** [comment]
Maybe you mean that^?

**Comment by aphyr** [comment]
Hehe, thanks @AeroNotix, I actually went and fixed it just now. Sorry for the dup!
