### ISSUE TITLE
*config-file* does not get bound to an included file when processing a directory

### ISSUE THREAD

**Issue by blalor** [aphyr/riemann#403]
```clojure
; /etc/riemann/riemann.conf

(info "loading" *config-file*) ;; → "loading /etc/riemann/riemann.conf"
(include "conf.d")

; /etc/riemann/conf.d/foo.conf
(info "loading" *config-file*) ;; → "loading /etc/riemann/conf.d"
```

That last `(info)` statement should return `/etc/riemann/conf.d/foo.conf`.

Binding is not set correctly for files: https://github.com/aphyr/riemann/blob/6ea82e07b0e409e20f431fdfbcc87cd02b0b4466/src/riemann/config.clj#L331

**Comment by zackdever** [comment]
Curious if anyone has a workaround to still allow relative includes when the first include is a directory?

**Comment by aphyr** [comment]
Faster to just patch the darn thing. Stand by.

**Comment by zackdever** [comment]
Thanks!
