### ISSUE TITLE
InfluxDB should be async

### ISSUE THREAD

**Issue by blalor** [aphyr/riemann#411]
The InfluxDB stream makes a request (via HTTP) to the InfluxDB server for every event.  There doesn't appear to be any provision for batching requests.  I don't think this will scale.  The capacitor library has an async operating mode.

```clojure
(require 'capacitor.core)
(require 'capacitor.async)
(require 'clojure.core.async)

(defn make-async-influxdb-client [opts]
    (let [client (capacitor.core/make-client opts)
        
          ;; Make a channel to buffer influxdb events
          events-in (capacitor.async/make-chan)
          
          ;; Make a channel to collect influxdb responses (ignored, really)
          resp-out (capacitor.async/make-chan)]

        ;; Start the run loop with a batch size of max 100 events and max 10
        ;; seconds
        (capacitor.async/run! events-in resp-out client 100 10000)

        (fn [series payload]
            (let [p (merge payload {
                    :series series
                    :time   (* 1000 (:time payload)) ;; s → ms
                })]
                
                (clojure.core.async/put! events-in p)
            )
        )
    )
)

(def influx (make-async-influxdb-client {
        :host     "some-host"
        :port     80
        :username "user"
        :password "pass"
        :db       "db"
    })
)

(streams
        (fn [event]
            (let [series (format "riemann.%s.%s" (:host event) (:service event))]
                (influx series {
                    :time  (:time event)
                    :value (:metric event)
                })
            )
        )
)
```

I'll contribute refactored InfluxDB support, but I wanted to make sure I got the basics captured.  I think it'll be necessary to do `(capacitor.async/close! events-in)` on a reload.  Not sure how to go about that, yet.

**Comment by aphyr** [comment]
Returning to this thread--I *don't* want to push each user into learning a new set of asynchronous semantics, options, and composition rules for each adapter. I *do* think we can readily address the problem of InfluxDB not supporting batches of events, and in conjunction with async-queue, I think that should address the immediate performance concerns.

Can I get someone who actually has Influx running to try f3fe6e2? The InfluxDB tests don't actually assert anything, which makes it tough for me to have confidence my changes are safe. If someone (@blalor? @arnaudbriche?) wants to add a simple mock test or three, I'd be thrilled. There's an example here!

https://github.com/aphyr/riemann/blob/a179c0739a68f6374d099dea616e3a9a3c7b4571/test/riemann/keenio_test.clj#L9

**Comment by fhalim** [comment]
Can confirm that I'm able to do (batch 500 1 (influxdb ...)) with current master. Made my InfluxDB server much happier :)

**Comment by kri5** [comment]
@fhalim Can you provide an full example, i am actually using capacitor, and i would prefer use batch instead, and i can't get it working :(

I'm running riemann 0.2.9

**Comment by fhalim** [comment]
@kri5 My config looks like this

```clojure
(def influxdb-baseconfig {:host "localhost"
                          :port 8086
                          :username "riemann"
                          :password "password"
                          :db "riemann-data"})

(defn namedidb [name]
  (batch 500 1 (influxdb
    (merge influxdb-baseconfig {:series (fn [opts] name)}))))
````
and I just write out to a ``` (namedidb "foo")```

**Comment by aphyr** [comment]
Looks like we're good here. :)
