### ISSUE TITLE
RPM package does not work on CentOS 7

### ISSUE THREAD

**Issue by fbor** [aphyr/riemann#453]
Due to new use of systemd, the RPM package doesn't work actually.
fatrpm.clj need to be changed to avoid daemonize dependency.

**Comment by icambron** [comment]
And back to the original problem, doing this (taken from the Fedora issue @mfournier posted) worked fine for me:

```
yum install -y https://kojipkgs.fedoraproject.org//work/tasks/4028/8784028/daemonize-1.7.3-7.el7.x86_64.rpm
yum install -y https://aphyr.com/riemann/riemann-0.2.8-1.noarch.rpm
```

**Comment by fbor** [comment]
Thanks, great news

**Comment by zzamboni** [comment]
In case anyone comes looking, the URL for that package is no longer valid. The new valid URL is https://kojipkgs.fedoraproject.org//packages/daemonize/1.7.3/7.el7/x86_64/daemonize-1.7.3-7.el7.x86_64.rpm

**Comment by nothing-fr** [comment]
http://mirrors.karan.org/epel7/Packages/daemonize/20131231020837/1.7.3-1.el6.x86_64/daemonize-1.7.3-1.el7.x86_64.rpm

**Comment by faxm0dem** [comment]
yeah well installing a random package doesn't solve the underlying issue
daemonize is not available in epel7 and probably won't be

**Comment by jamtur01** [comment]
@faxm0dem I've asked the maintainer to push the package (https://bugzilla.redhat.com/show_bug.cgi?id=1144474). It's just been a bit slow I think rather than being a lost cause. If it makes you more comfortable there is a semi-sanction build here: http://koji.fedoraproject.org/koji/taskinfo?taskID=8784026

**Comment by faxm0dem** [comment]
@jamtur01 okay nice, never mind I just built my own using the above SRPM

**Comment by ajsmith** [comment]
This issue was never resolved. The daemonize dependency still doesn't exist in CentOS / RHEL 7, and installation is still broken on those systems. Some people managed a workaround by building or installing an unofficial daemonize package, but this issue still very much exists.

**Comment by ajsmith** [comment]
Oops, I must have got a wire crossed or something. This is working for me now with the latest EPEL packages. Please disregard my previous comment.
