### ISSUE TITLE
Question on configuration - pipeline event 

### ISSUE THREAD

**Issue by yesnault** [aphyr/riemann#486]
Hi,

I tried to monitor one or two hundred of services and for some services, I want to compute the state field.

```
            -B''--C''----
 A       B /             \
----------/ -B'---C----------E---- F
          \              /
           \ B'''--C'''--
```

A : a event arrives in Riemann
B : if a event is service foo, go to pipeline B
B : if a event is service foo2, go to pipeline B''
B : if a event is another service, go to pipeline B'''
C'' : compute state of event. If metric > 90, state="critical"
C''' : compute state of event. If metric > 80, state="critical"
C : compte state : state="empty"
E : Compute change state, send mail if critical (1 mail per 10min)
F : send to influxdb

So, how can I do for having B'' and B''' in a dedicated configuration file (I can have one hundred different configuration) ? With simple where clause, an event  passes through B'' and B', how can I avoid that (to not send 2 events for the same metric to InfluxDB at the end) ?

Thanks a lot !

**Comment by aphyr** [comment]
On 01/07/2015 01:25 AM, Yvonnick Esnault wrote:
> Hi,
>
> I tried to monitor one or two hundred of services and for some services, I want
> to compute the state field.
>
> |             -B''--C''----
>   A       B /             \
> ----------/ -B'---C----------E---- F
>            \              /
>             \ B'''--C'''--
> |
>
> A : a event arrives in Riemann
> B : if a event is service foo, go to pipeline B
> B : if a event is service foo2, go to pipeline B''
> B : if a event is another service, go to pipeline B'''
> C'' : compute state of event. If metric > 90, state="critical"
> C''' : compute state of event. If metric > 80, state="critical"
> C : compte state : state="empty"
> E : Compute change state, send mail if critical (1 mail per 10min)
> F : send to influxdb
>
> So, how can I do for having B'' and B''' in a dedicated configuration file (I
> can have one hundred different configuration) ? With simple where clause, an
> event passes through B'' and B', how can I avoid that (to not send 2 events for
> the same metric to InfluxDB at the end) ?

I'm not sure I understand your question, but it sounds like you might be looking 
for http://riemann.io/howto.html#combine-streams; split or splitp might be 
useful in routing each event to exactly one branch, and pipe can recombine them 
afterwards.

--Kyle

**Comment by yesnault** [comment]
Yes, indeed, my question was not very clear :) I'll try to work with split(p) and pipe (and include), and open re-open this issue if necessary.
