### ISSUE TITLE
doc improvement suggestion: which is the authoritative protocol buffer definition?

### ISSUE THREAD

**Issue by khigia** [aphyr/riemann#503]
I look around in Riemann source code and couldn't find a ".proto" file (not sure if it is using dynamic protobuf capability).
Is there an authoritative source of proto definition? I saw few client referring to aphyr/riemann-java-client proto file, if it is the main definition source, it might be worth adding to the doc/website ... or maybe I missed that in the doc?

thanks!

**Comment by aphyr** [comment]
http://riemann.io/howto.html#write-a-client
