### ISSUE TITLE
Problem querying index: values shows up only after reloading config file (sighup)

### ISSUE THREAD

**Issue by joelapatatechaude** [aphyr/riemann#513]
Hi There,

I am essentially running the following clojure file:
```clojure
(let [host "127.0.0.1"]
  (tcp-server {:host host})
  (ws-server  {:host host}))

(instrumentation {:interval 5 :enabled? false})

;; index everything
(let [index (index)]
  (streams
   index))

;; Part1.
(streams
 (where (and (service "/sysconf/userhz") (host "my-node-id"))
        #(info "1. User Hertz in stream "
               (:metric %)
               "User Hertz in index"
               (:metric (riemann.index/lookup (:index @core) "my-node-id" "/sysconf/userhz")))))

;; Part2.
(let [index (index)]
  (streams
   (where (and (service "/sysconf/userhz") (host "my-node-id"))
          #(info "2. User Hertz in stream "
                 (:metric %)
                 "User Hertz in index"
                 (:metric (riemann.index/lookup (:index @core) "my-node-id" "/sysconf/userhz"))))))
```
I am probably doing something silly with the index, but this is what I am observing:
A. If I remove Part2, Part1 works fine (the lookup returns a value)
B. If I keep Part1 and Part2, both lookup returns nill
C. If I keep Part1 and Part2, and If after starting Riemann, I emit a SIGHUP, both Part1 and Part2 works fine.

I would love some explanations so I understand better Riemann and why A. and B. On the other hand, C. sounds very strange.

Thanks!

**Comment by aphyr** [comment]
You've defined two distinct indexes here; Riemann will only use one of them for queries. Move your part2 streams inside the let binding so they use the first index.

**Comment by joelapatatechaude** [comment]
Can I define more than 1 index, and query againt the one I want?

**Comment by aphyr** [comment]
You can define as many indices as you like, but no, Riemann's query system only uses one. It's supposed to be a global view of your system.

**Comment by joelapatatechaude** [comment]
Fair enough, thanks!
