### ISSUE TITLE
Delete old log files

### ISSUE THREAD

**Issue by juise** [aphyr/riemann#556]
Hi!

Looks like for time based rolling policy (TimeBasedRollingPolicy) don't enabled number of backup log files like for fixed window rolling policy (FixedWindowRollingPolicy) via (.setMaxIndex 5). It's seems like a little bit inconsistent for me.

May be we can additionaly use maxBackupIndex from RollingFileAppender for both  TimeBasedRollingPolicy and FixedWindowRollingPolicy?

**Comment by juise** [comment]
If the suggested way will be Okay, I can make pull request for this feature.

**Comment by aphyr** [comment]
Sounds OK to me.
On May 18, 2015 7:23 AM, Alexander Petrovsky <notifications@github.com> wrote:If the suggested way will be Okay, I can make pull request for this feature.

**Comment by juise** [comment]
I'm finally started working on this issue, and stumbled upon two different versions 'RollingFileAppender' one from org.apache.log4j.rolling (used in Riemann) and one from org.apache.log4j.

I find out that we can't delete old rotated files not from RollingFileAppender nor TimeBasedRollingPolicy.

Do you mind to try use logback instead log4j? What do you think about it?

**Comment by aphyr** [comment]
I think we're gonna gut this code in favor of @pyr's logging stuff. @pyr?

**Comment by juise** [comment]
If @pyr's version based on logback and support file rotation for timebased and sizebased policy it's will be great!
