### ISSUE TITLE
tapped index allows duplicate host/service pairs

### ISSUE THREAD

**Issue by mfournier** [aphyr/riemann#565]
```
(let [index (tap :index (index))]
  (streams index))

(tests
  (deftest index-test
    (let [index (:index (inject! [
      {:host "host1" :service "service1" :ttl 10 :time 1}
      {:host "host1" :service "service1" :ttl 10 :time 2}
      {:host "host1" :service "service1" :ttl 10 :time 3}
    ]))]
    (clojure.pprint/pprint index))))
```

```
Testing riemann.config-test
[{:service "service1", :time 1, :host "host1", :ttl 10}
 {:service "service1", :time 2, :host "host1", :ttl 10}
 {:service "service1", :time 3, :host "host1", :ttl 10}]

Ran 1 tests containing 0 assertions.
0 failures, 0 errors.
```

The real index won't allow you to have multiple identical host/service pairs.

In this regard, depending on what/how you test, you'd get a different result than when running riemann for real.

In any case, thanks again for implementing streams testability, it's really super useful to me !

**Comment by aphyr** [comment]
This is by design: taps show you every event that flows through them. They don't change their behavior based on their child streams--and if they did, you wouldn't be able to make assertions about the intermediate state of the index; only the final state.

**Comment by mfournier** [comment]
Thanks for the clarification @aphyr ! It indeed makes sense.
