### ISSUE TITLE
How to enable InfluxDB 0.9 support intoduced in 0.2.10?

### ISSUE THREAD

**Issue by Kenuat** [aphyr/riemann#587]
Hi, code from my config:
```
      (influxdb {:host "10.13.36.119"
                 :port 8086
                 :db "riemann"
                 :series #(str (:host %) "." (:service %))})
```
It result in the following request:
```
http://10.13.36.119:8086/db/riemann/series?u=root&p=root&time_precision=s
```
which is obviously in InfluxDB 0.8 version format
How should I send data to 0.9 InfluxDB?

Thanks in advance.

**Comment by pradeepchhetri** [comment]
@Kenuat You need to set `:version` to `:0.9` (default: `:0.8`)

**Comment by Kenuat** [comment]
@pradeepchhetri Thanks for the help, think I had to look through the script on my own tho :)
