### ISSUE TITLE
Consider switching from log4j?

### ISSUE THREAD

**Issue by kokje** [aphyr/riemann#588]
It seems like log4j doesn't support both time and size based rotation. I looked org.apache.log4j.rolling.FixedWindowRollingPolicy.java and org.apache.log4j.rolling.TimeBasedRollingPolicy.java on github and each of them rename the files by calling getIntegerPatternConverter and getDatePatternConverter respectively. So it looks like you can have one or the other but not both.

**Comment by pyr** [comment]
Hi!

Riemann will ultimately switch to https://github/pyr/unilog to address this

On July 25, 2015 3:00:33 AM CEST, Yashashree Kokje <notifications@github.com> wrote:
>It seems like log4j doesn't support both time and size based rotation.
>I looked org.apache.log4j.rolling.FixedWindowRollingPolicy.java and
>org.apache.log4j.rolling.TimeBasedRollingPolicy.java on github and each
>of them rename the files by calling getIntegerPatternConverter and
>getDatePatternConverter respectively. So it looks like you can have one
>or the other but not both.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/aphyr/riemann/issues/588

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kokje** [comment]
Sounds good, thanks for letting me know!
