### ISSUE TITLE
question

### ISSUE THREAD

**Issue by kolbykinzer** [aphyr/riemann#591]
I am looking for a way to alert only when something happens a certain amount of times in an hour. so, say this something happened 3 times in one hour I want just one alert. Subsequently that time window would restart with every alert. I am relitivley new to clojure and riemann. any help would be greatly appreciated. thank you

**Comment by jamtur01** [comment]
These might help: http://riemann.io/howto.html#group-events-in-time and http://riemann.io/howto.html#alerting-when-a-certain-percentage-of-events-happe. Also the mailing list is a good place to ask: https://groups.google.com/forum/#!forum/riemann-users.

**Comment by kolbykinzer** [comment]
thank you for the fast response on that, so after taking in your advice .. this is what I have come up with. it not working too well. haha any other pointers would be great. 

(let [email (throttle 1 3600 (mailer {:from "myemail"}))]
(streams
    (where (description #"what I am looking for")
      (moving-time-window 3600
        (smap (fn [events]
                (let [example-count (count events)]
                   {:service"counting-example"
                    :metric example-count
                    :state (if (< example-count 3) "ok" "warning")
                    :description"We have reached 3 times within the hour.."
                    :ttl 30}))
                (changed :state (email "myemail")))))))

**Comment by kolbykinzer** [comment]
thank you for the fast response, so after taking your advice this is what I've com up with and it does not seem to be working. any further advice or pointers would be great, thank you. 


         
![capture](https://cloud.githubusercontent.com/assets/8999867/9316116/65465f9c-44f0-11e5-8c1e-403402244b4f.PNG)

**Comment by aphyr** [comment]
This looks reasonable to me, except it looks like you're treating (email) as a mailer twice? Think you just want `email`, not `(email "myemail")`.

**Comment by kolbykinzer** [comment]
well what I was trying to do was just get an email from myself by putting my email in both those spots. shouldnt that work?

**Comment by aphyr** [comment]
Ah, yeah, that's not how mailer works. If you look at the mailer docs, it returns a stream constructor that takes the destination email address. Instead, you're invoking the stream (throttle) constructed with an email address.

**Comment by kolbykinzer** [comment]
so, should that work if i took throttle out of this?

**Comment by aphyr** [comment]
Or thread the email op past throttle and into the mailer.

**Comment by Kenuat** [comment]
@aphyr have you considered creating user driven knowledge base for riemann best practices (like those in http://riemann.io/howto.html)? I mean most of the riemann users never programmed clojure or any other functional language, entry barrier for riemann for them (for us) is a way too hight

**Comment by aphyr** [comment]
The howto has a documented contrib process, but I'm trying to keep the docs relatively well-gardened so I'd like to avoid a wiki or similar. Poorly written or out-of-date docs wind up being a support burden that falls on, well, pretty much me. :-/

**Comment by kolbykinzer** [comment]
sorry for the late response, so I have this and seem to get no response from it. 

![riemann_code](https://cloud.githubusercontent.com/assets/8999867/9337369/3be61532-459c-11e5-803e-e46bd70e941f.PNG)

it is getting logs from syslog-ng they are reaching riemann, it prints the out put in riemann, just no email on the events happening x times in hour. her is the syslog code, I hard coded the description from now. and then ill show you the riemann out put. let me know what you think. thank you 

![syslog-ng-config](https://cloud.githubusercontent.com/assets/8999867/9337461/bc4061d8-459c-11e5-82fd-92970f32af32.PNG)

![output](https://cloud.githubusercontent.com/assets/8999867/9337498/ee8f76f6-459c-11e5-831b-be0c86cedcc9.PNG)

**Comment by aphyr** [comment]
`tell-ops` is already a stream, and you're invoking it with `(tell-ops)` later on. I think you just want `tell-ops`.

**Comment by kolbykinzer** [comment]
I tried that, didnt work so I changed tell-ops to prn to see if it is actually changing state. It  does not look like the change state is even detecting anything, or it is just not changing state.

**Comment by aphyr** [comment]
It looks like you've also got some misplaced parens? You probably want changed-state as a child of smap...

**Comment by kolbykinzer** [comment]
awesome !! that was it, thank you.
